#ifndef DEFINES_H
#define DEFINES_H

#define MAP_WIDTH   40
#define MAP_HEIGHT  40

#define TILE_SIZE   16

#define WWIDTH      640
#define WHEIGHT     800

// PLAYER STUFF
#define PLAYER_LIFE     100
#define PLAYER_SPEED    15
#define PLAYER_START_XPOSITION 300
#define PLAYER_START_YPOSITION 400
#define PLAYER_BULLET1_SHOOT_DELAY 100

// BACKGROUND STUFF
#define BACKGROUND_SCROLL_SPEED_LEVEL_1 1
#define BACKGROUND_SCROLL_SPEED_LEVEL_2 2
#define BACKGROUND_SCROLL_SPEED_LEVEL_3 3
#define BACKGROUND_SCROLL_SPEED_LEVEL_4 4

// SFX
#define SFX_AUDIO_CHANNEL_LASER 1
#define SFX_AUDIO_CHANNEL_DEATH 2

#endif // DEFINES_H
 